import Head from "next/head";
import Image from "next/image";
import HomeScreen from "../components/HomeScreen";

export default function Home() {
	return (
		<div className="bg-black">
			<Head>
				<title>Netflix</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<HomeScreen />
		</div>
	);
}
